version: 5.44.{build}
image:
  - Visual Studio 2022
  - Ubuntu2004

environment:
  AppVeyorApi:
    secure: e9BtF4uHDk3PxumsQHVK6I5GXlIh0IN2Gq1BBetSJx8=
  NuGetApiKey:
    secure: tAdUQmRiZ270LOPN8SwbjISLfu6ldDTw6LWvdtsk+pQR7r5bJnGrG8Ntyt87edJ/
  AzureServicePrincipal:
    secure: +TRxhGVtAWxPEiDoHfsxMr/9U4JlCJQ4h7loqVJnlDoDg4YlxgIgsovw0N3BdWUaARkOX2HwTlfZ1iurg2W7yBxNKZ5z0UUGEXoUAkteqnslQUd5siuCbRVkAhiLtbxGHdAjLM+3sMLfMQgrzWFC2JI+WEO/Fmjlp101tVWevRM0ybMdnxFxMisj0x6axnSbgX03/J//ikC4FHzVYk1hoF9nX7QACbqKwC4hF69wLA5LHkMfpui3EWwy2pQXCQSpX5cgLV9mHHr+iGpXSbLL/XLX7KZ0+HYYHNeaYL7p65vxt6TcfOO01vTZDvYQNn7B9hL+ik6ENhl9bNOTjRT+u49anLoLcO/nYdzX/mDigilXxJVh0v/BvWO+54tYHmxr0VD3XzUQTZg6B01cO/GkLMpj5NJCaU7s5pXgdwdNrGlkPSkgx2FC6yoPhLEDJoYXvhybwnQsoLJoJL5uBvwo+jRNZHrT+TP6Qy7NkCp/IqqIyrR0Cmsk9Mkq7h9KkvR3



branches:
  except:
    - /(?i).*release.*/

skip_tags: true

install:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER/.build/install.ps1"

dotnet_csproj:
  patch: true
  file: '**\LabXml.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER/.build/beforebuild.ps1"

for:
  - matrix:
      only:
        - image: Visual Studio 2022
    build:
      project: AutomatedLab.sln
    deploy:
      - provider: GitHub
        description: "This is an automated deployment"
        auth_token:
          secure: HsE6rIUR/bsL7wBhrBgfFf3HFDkiqASb96bKgW34XOZVjLUYVIq/yFAVs1a5Ydxy # your encrypted token from GitHub
        artifact: alinstaller
        draft: false
        force_update: true
        prerelease: false
        on:
          branch: master
  - matrix:
      only:
        - image: Ubuntu2004
    build_script: dotnet build -f net6.0 LabXml/LabXml.csproj
    deploy:
      - provider: GitHub
        description: "This is an automated deployment"
        auth_token:
          secure: HsE6rIUR/bsL7wBhrBgfFf3HFDkiqASb96bKgW34XOZVjLUYVIq/yFAVs1a5Ydxy # your encrypted token from GitHub
        artifact: aldebianpackage
        draft: false
        force_update: true
        prerelease: false
        on:
          branch: master
      - provider: GitHub
        description: "This is an automated deployment"
        auth_token:
          secure: HsE6rIUR/bsL7wBhrBgfFf3HFDkiqASb96bKgW34XOZVjLUYVIq/yFAVs1a5Ydxy # your encrypted token from GitHub
        artifact: alrpmpackage
        draft: false
        force_update: true
        prerelease: false
        on:
          branch: master

after_build:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER/.build/afterbuild.ps1"
  - ps: "& $env:APPVEYOR_BUILD_FOLDER/.build/afterdeploy.ps1"

on_finish:
  - ps: "& $env:APPVEYOR_BUILD_FOLDER/.build/onfinish.ps1"
